mongo-uri: "mongodb://localhost:27017"
telegram-api-token: "6284815139:AAHSgQPzvyhlRYmLluDFeJjeEf6YyaI5Ml0"
bot-messages:
  permission-prefix-full: "[‚úÖ] –°–∏—Å—Ç–µ–º–∞ —É—Å–ø–µ—à–Ω–æ —Ç–µ–±—è —Ä–∞—Å–ø–æ–∑–Ω–∞–ª–∞, –¥–æ—Å—Ç—É–ø —Ä–∞–∑—Ä–µ—à–µ–Ω.\n
–¢–≤–æ–π —É—Ä–æ–≤–µ–Ω—å –¥–æ—Å—Ç—É–ø–∞: $ROLE$\n
  \n
  ---------------------------------------------------------\n
  \n"
  permission-prefix-minimum: "[‚úÖ] –î–æ—Å—Ç—É–ø: $ROLE$; $NAME$\n\n"
  clock-prefix: "| [–ß–∞—Å—ã] ‚öúÔ∏è"
  order-prefix: "| [–ó–∞–∫–∞–∑—ã] üë®‚Äçüíª"
  global-prefix: "| [NixieTech] "
  initial-help-message: "
  $permission-prefix-full$
  –î–æ–±—Ä–æ –ø–æ–∂–∞–ª–æ–≤–∞—Ç—å, $NAME$!‚ù§Ô∏è‚Äçüî•\n
  \n
  –Ø —Å–æ–∑–¥–∞–Ω –¥–ª—è —É–ø—Ä–∞–≤–ª–µ–Ω–∏—è –∏–Ω—Ç–µ—Ä—Ñ–µ–π—Å–∞–º–∏ —Å–∞–π—Ç–∞ —Ç–≤–æ–µ–π –∫–æ–º–ø–∞–Ω–∏–∏. –î–∞–≤–∞–π —è —Ç–µ–±–µ –æ–±—ä—è—Å–Ω—é, –∫–∞–∫ –º–Ω–æ—é —É–ø—Ä–∞–≤–ª—è—Ç—å? –ù–∞ —Å–∞–º–æ–º –¥–µ–ª–µ —ç—Ç–æ –Ω–µ—Å–ª–æ–∂–Ω–æ.üíé\n
  \n
  –ü—Ä–æ—Å—Ç–æ –Ω–∞–∂–∏–º–∞–π –Ω–∞ –Ω—É–∂–Ω—ã–µ –∫–Ω–æ–ø–∫–∏ –∏ —Å–ª–µ–¥—É–π –∏–Ω—Å—Ç—Ä—É–∫—Ü–∏—è–º - –≤—Å–µ —Å–º–æ–∂–µ—à—å!‚öúÔ∏è\n
  \n
  developed by thestrikem
  "
  show-menu-message: "–ü—Ä–æ—Å—Ç–æ –Ω–∞–∂–∏–º–∞–π –Ω–∞ –Ω—É–∂–Ω—ã–µ –∫–Ω–æ–ø–∫–∏ –∏ —Å–ª–µ–¥—É–π –∏–Ω—Å—Ç—Ä—É–∫—Ü–∏—è–º - –≤—Å–µ —Å–º–æ–∂–µ—à—å!‚öúÔ∏è\n
  \n 
  DBT"

  clock-menu-message: "$permission-prefix-minimum$
  $PREFIX$\n\n
  –¢–∞–∫, –≤–∫–ª—é—á–µ–Ω —Ä–µ–∂–∏–º —É–ø—Ä–∞–≤–ª–µ–Ω–∏—è —á–∞—Å–∞–º–∏, —Ç—ã –º–æ–∂–µ—à—å —É–¥–∞–ª—è—Ç—å, –¥–æ–±–∞–≤–ª—è—Ç—å –∏ —Ä–µ–¥–∞–∫—Ç–∏—Ä–æ–≤–∞—Ç—å –º–æ–¥–µ–ª–∏ —á–∞—Å–æ–≤‚öúÔ∏è"
  order-menu-message: "$permission-prefix-full$
  $PREFIX$\n\n
  –¢–∞–∫, –≤–∫–ª—é—á–µ–Ω —Ä–µ–∂–∏–º —É–ø—Ä–∞–≤–ª–µ–Ω–∏—è –∑–∞–∫–∞–∑–∞–º–∏, —Ç—ã –º–æ–∂–µ—à—å –∑–∞–∫—Ä—ã—Ç—å –∑–∞–∫–∞–∑, –ø–æ–ø—Ä–æ—Å–∏—Ç—å –æ—Ç–æ–±—Ä–∞–∑–∏—Ç—å –∑–∞–∫–∞–∑ –≤ —É–¥–æ–±–Ω–æ–º –≤–∏–¥–µ üë®‚Äçüíª‚Äç"
  clock-item-message: "[‚öúÔ∏è] –ß–∞—Å—ã $CLOCK_NAME$, –¶–µ–Ω–∞ - $CLOCK_PRICE$‚ÇΩ, –í –Ω–∞–ª–∏—á–∏–∏ - $CLOCK_EXISTENCE$, –¢–∏–ø —á–∞—Å–æ–≤ - $CLOCK_TYPE$"
  clock-create-start: "–û—Ç–ª–∏—á–Ω–æ, –≤–≤–µ–¥–∏—Ç–µ —á–µ—Ä–µ–∑ –∑–∞–ø—è—Ç—É—é —Å–≤–æ–π—Å—Ç–≤–∞ —á–∞—Å–æ–≤, —Ñ–æ—Ä–º–∞—Ç:\n–ò–º—è;–¶–µ–Ω–∞;–í –Ω–∞–ª–∏—á–∏–∏(‚úÖ;‚ùå);–¢–∏–ø —á–∞—Å–æ–≤\n–ü—Ä–∏–º–µ—Ä: –ß–∞—Å—ã-1;19000;‚úÖ;2"
  clock-show-all: "
  $permission-prefix-minimum$
  $PREFIX$\n\n
  –ü–æ —Ç–≤–æ–µ–º—É –∑–∞–ø—Ä–æ—Å—É, –¥—Ä—É–≥ –º–æ–π, –≤—ã–≤–æ–∂—É –≤—Å–µ —á–∞—Å—ã, –Ω–∞—Ö–æ–¥—è—â–∏–µ—Å—è –≤ –Ω–∞—Å—Ç–æ—è—â–µ–µ –≤—Ä–µ–º—è –≤ –±–∞–∑–µ –¥–∞–Ω–Ω—ã—Ö‚öúÔ∏è
  "
  create-clock-finish: "–ß–∞—Å—ã $CLOCK_NAME$, –¶–µ–Ω–∞ - $CLOCK_PRICE$‚ÇΩ, –í –Ω–∞–ª–∏—á–∏–∏ - $CLOCK_EXISTENCE$, –¢–∏–ø —á–∞—Å–æ–≤ - $CLOCK_TYPE$ - —É—Å–ø–µ—à–Ω–æ —Å–æ–∑–¥–∞–Ω—ã‚úÖ"
  confirm-delete-clock: "
  $permission-prefix-minimum$
  $PREFIX$\n\n
  –ë—Ä–∞—Ç–∏–∫, –ø–æ–¥—Ç–≤–µ—Ä–¥–∏ —É–¥–∞–ª–µ–Ω–∏–µ —á–∞—Å–æ–≤ —Å $CLOCK_NAME$\n
  –ù–∞–ø–∏—à–∏ \"–î–∞\", —á—Ç–æ–±—ã —É–¥–∞–ª–∏—Ç—å"
  start-update-clock: "
  $permission-prefix-minimum$
  $PREFIX$\n\n
  –¢—ã —Ö–æ—á–µ—à—å –∏–∑–º–µ–Ω–∏—Ç—å —á–∞—Å—ã —Å $CLOCK_NAME$\n\n
  –§–æ—Ä–º–∞—Ç: –ù–∞–∑–≤–∞–Ω–∏–µ;–¶–µ–Ω–∞;–í –Ω–∞—á–∞–ª–∏–∏—á–∏–∏;–¢–∏–ø —á–∞—Å–æ–≤ 
  d - –æ—Å—Ç–∞–≤–∏—Ç—å –±–µ–∑ –∏–∑–º–µ–Ω–µ–∏–π
  
  –ü—Ä–∏–º–µ—Ä –∑–∞–ø—Ä–æ—Å–∞: d;1000000000;‚úÖ;d
  "
  success-deleted-clock: "–ß–∞—Å—ã —É—Å–ø–µ—à–Ω–æ —É–¥–∞–ª–µ–Ω—ã"
  order-item-message: "[üë®‚Äçüíª] –ó–∞–∫–∞–∑ $ORDER_NAME$, –¶–µ–Ω–∞ - $ORDER_PRICE$, "
  remove-item-storage: "–î–µ–π—Å—Ç–≤–∏–µ –±—ã–ª–æ –æ—Ç–º–µ–Ω–µ–Ω–æ"
  undefined-message: "–û–±—Ä–∞–±–æ—Ç—á–∫ –Ω–µ –º–æ–∂–µ—Ç —Ä–∞—Å–ø–æ–∑–Ω–∞—Ç—å –≤–∞—à–µ —Å–æ–æ–±—â–µ–Ω–∏–µ"
  # "–ò–ú–Ø;–ü–æ–∫–∞–∑—ã–≤–∞—Ç—å –º–µ–Ω—é —á–∞—Å–æ–≤;–°–æ–∑–¥–∞–≤–∞—Ç—å —á–∞—Å—ã;–†–µ–¥–∞–∫—Ç–∏—Ä–æ–≤–∞—Ç—å —á–∞—Å—ã;–£–¥–∞–ª—è—Ç—å —á–∞—Å—ã;–ü–æ—Å–º–æ—Ç—Ä–µ—Ç—å –º–µ–Ω—é –∑–∞–∫–∞–∑–æ–≤;–£–¥–∞–ª—è—Ç—å –∑–∞–∫–∞–∑—ã"
  # –ø—Ä–∏–º–µ—Ä: "–ú–µ–Ω–µ–¥–∂–µ—Ä;‚úÖ;‚úÖ;‚ùå;‚úÖ;‚ùå"
  permission-groups: [
    "–ü–æ–ª–Ω—ã–πüëë;‚úÖ;‚úÖ;‚úÖ;‚úÖ;‚úÖ;Kartonios,thestrikem,leorended",
    "–ú–µ–Ω–µ–¥–∂–µ—ÄüìÇ;‚úÖ;‚ùå;‚ùå;‚ùå;‚úÖ;‚úÖ;kil,vasya337",
  ]
  permission-denied: "–£ –≤–∞—Å –Ω–µ—Ç –ø—Ä–∞–≤ –Ω–∞ —ç—Ç–æ –¥–µ–π—Å—Ç–≤–∏–µ - ‚ùå"